### ISSUE TITLE
room cleaning issue

### ISSUE THREAD

**Issue by ARNAB5671** [mridul-g/New-HallBuddy#6]
one student can lodge a complain for other student... and the manager wont know who lodged the complaint

**Comment by mridul-g** [comment]
This is supposed to happen as in daily sometimes room owner is not in his room but a friend gets his room cleaned on his behalf. So to mark this we have implemented it as such.

**Comment by ARNAB5671** [comment]
but manager should know who lodged the complaint ?

**Comment by mridul-g** [comment]
> but manager should know who lodged the complaint ?

Are you talking about complaint or room cleaning.
in either case userid of the user is displayed along.
